### PR TITLE
Add C wrappers

### PR DESCRIPTION
**Pull request by IvanUkhov**
The pull request complements issue #15.

### CODE REVIEW

**Comment by IvanUkhov** [comment]
@cmr, I have two questions.

1. How do you like splitting the packages into two modules, `c` and `fortran`, so that the user has to do what is shown in the two examples given [here](https://github.com/stainless-steel/blas/tree/cblas)?

2. What do you think about eliminating the `cblas_` prefix (just like the `_` suffix was eliminated for Fortran) and polishing the naming of CBLAS enums (see starting from [here](https://github.com/stainless-steel/blas/blob/cblas/src/c.rs#L27))?

Thanks!

**Comment by cmr** [comment]
@IvanUkhov I like both of those things!

**Comment by IvanUkhov** [comment]
@cmr and @bluss, in case you’re interested, [here](https://travis-ci.org/stainless-steel/blas/builds/104413057) is some benchmarking of `dgemv` with respect to the C and Fortran interfaces. `_cm_` stands for “column major,” and `_rm_` for “row major.” I’m not sure, though, how comparable Travis’ containers are.

## OS X, Accelerate

```
test c::dgemv_cm_00010    ... bench:          72 ns/iter (+/- 27)
test c::dgemv_cm_00100    ... bench:       5,121 ns/iter (+/- 4,527)
test c::dgemv_cm_01000    ... bench:   1,367,517 ns/iter (+/- 628,771)
test c::dgemv_cm_10000    ... bench:  84,767,116 ns/iter (+/- 49,811,003)
test c::dgemv_rm_00010    ... bench:          67 ns/iter (+/- 14)
test c::dgemv_rm_00100    ... bench:       2,841 ns/iter (+/- 611)
test c::dgemv_rm_01000    ... bench:     429,500 ns/iter (+/- 56,866)
test c::dgemv_rm_10000    ... bench:  59,225,089 ns/iter (+/- 9,588,402)
test fortran::dgemv_00010 ... bench:          70 ns/iter (+/- 11)
test fortran::dgemv_00100 ... bench:       3,248 ns/iter (+/- 1,564)
test fortran::dgemv_01000 ... bench:     523,825 ns/iter (+/- 31,643)
test fortran::dgemv_10000 ... bench:  68,996,040 ns/iter (+/- 7,418,354)
```

## OS X, Netlib

```
test c::dgemv_cm_00010    ... bench:         124 ns/iter (+/- 12)
test c::dgemv_cm_00100    ... bench:      12,702 ns/iter (+/- 14,097)
test c::dgemv_cm_01000    ... bench:   1,510,406 ns/iter (+/- 744,115)
test c::dgemv_cm_10000    ... bench: 207,825,825 ns/iter (+/- 115,369,231)
test c::dgemv_rm_00010    ... bench:         127 ns/iter (+/- 10)
test c::dgemv_rm_00100    ... bench:       9,989 ns/iter (+/- 410)
test c::dgemv_rm_01000    ... bench:   1,243,822 ns/iter (+/- 524,494)
test c::dgemv_rm_10000    ... bench: 154,893,602 ns/iter (+/- 35,050,955)
test fortran::dgemv_00010 ... bench:         119 ns/iter (+/- 46)
test fortran::dgemv_00100 ... bench:      12,556 ns/iter (+/- 4,401)
test fortran::dgemv_01000 ... bench:   1,500,180 ns/iter (+/- 1,368,571)
test fortran::dgemv_10000 ... bench: 171,569,686 ns/iter (+/- 28,871,155)
```

## OS X, OpenBLAS

```
test c::dgemv_cm_00010    ... bench:       7,550 ns/iter (+/- 2,695)
test c::dgemv_cm_00100    ... bench:      63,007 ns/iter (+/- 16,811)
test c::dgemv_cm_01000    ... bench:   1,372,079 ns/iter (+/- 1,335,216)
test c::dgemv_cm_10000    ... bench:  93,150,484 ns/iter (+/- 75,491,187)
test c::dgemv_rm_00010    ... bench:         106 ns/iter (+/- 89)
test c::dgemv_rm_00100    ... bench:       2,460 ns/iter (+/- 37,654)
test c::dgemv_rm_01000    ... bench:     266,237 ns/iter (+/- 25,355)
test c::dgemv_rm_10000    ... bench:  57,335,644 ns/iter (+/- 2,238,661)
test fortran::dgemv_00010 ... bench:       7,524 ns/iter (+/- 542)
test fortran::dgemv_00100 ... bench:      63,009 ns/iter (+/- 16,947)
test fortran::dgemv_01000 ... bench:   1,014,703 ns/iter (+/- 89,509)
test fortran::dgemv_10000 ... bench:  79,360,516 ns/iter (+/- 1,351,353)
```

## GNU/Linux, Netlib

```
test c::dgemv_cm_00010    ... bench:         125 ns/iter (+/- 22)
test c::dgemv_cm_00100    ... bench:       8,176 ns/iter (+/- 136)
test c::dgemv_cm_01000    ... bench:     694,677 ns/iter (+/- 41,764)
test c::dgemv_cm_10000    ... bench:  89,156,539 ns/iter (+/- 2,453,984)
test c::dgemv_rm_00010    ... bench:         107 ns/iter (+/- 0)
test c::dgemv_rm_00100    ... bench:       9,784 ns/iter (+/- 155)
test c::dgemv_rm_01000    ... bench:     999,182 ns/iter (+/- 20,195)
test c::dgemv_rm_10000    ... bench: 105,083,045 ns/iter (+/- 3,245,413)
test fortran::dgemv_00010 ... bench:         119 ns/iter (+/- 1)
test fortran::dgemv_00100 ... bench:       8,155 ns/iter (+/- 53)
test fortran::dgemv_01000 ... bench:     685,057 ns/iter (+/- 7,928)
test fortran::dgemv_10000 ... bench:  87,486,546 ns/iter (+/- 3,073,954)
```

## GNU/Linux, OpenBLAS

```
test c::dgemv_cm_00010    ... bench:          96 ns/iter (+/- 6)
test c::dgemv_cm_00100    ... bench:      19,546 ns/iter (+/- 6,705)
test c::dgemv_cm_01000    ... bench:     777,667 ns/iter (+/- 34,931)
test c::dgemv_cm_10000    ... bench:  64,727,593 ns/iter (+/- 11,359,552)
test c::dgemv_rm_00010    ... bench:         113 ns/iter (+/- 3)
test c::dgemv_rm_00100    ... bench:      19,802 ns/iter (+/- 931)
test c::dgemv_rm_01000    ... bench:     554,643 ns/iter (+/- 27,370)
test c::dgemv_rm_10000    ... bench:  62,450,408 ns/iter (+/- 8,886,606)
test fortran::dgemv_00010 ... bench:         114 ns/iter (+/- 64)
test fortran::dgemv_00100 ... bench:      26,128 ns/iter (+/- 2,037)
test fortran::dgemv_01000 ... bench:     912,451 ns/iter (+/- 55,085)
test fortran::dgemv_10000 ... bench:  64,187,889 ns/iter (+/- 13,341,614)
```

**Comment by cmr** [comment]
The error margins there are too big to make any reasonable comparisons. I suspect that will always be the case with travis - it's garbage for performance measurement because of how noisy the shared system is.

**Comment by bluss** [comment]
Some backends support row major equally as column major and others don't, then.

**Pull request merged**
